models:
  - name: RF
    params:
      n_estimators: 200
      max_depth: 10
  # - name: RF
  #   params:
  #     n_estimators: 100
  #     max_depth: 10
  - name: XGB
    params:
      n_estimators: 150
      learning_rate: 0.05
      max_depth: 6
  - name: SVM
    params:
      C: 1.0
      gamma: "scale"
